title: Jake Wilson
description: 
url: https://jkwlsn.com
author:
    name: Jacob Charles Wilson
    email: hi@jkwlsn.dev
    instagram: jcbchrlswlsn
    github: jkwlsn
    linkedin: jacobcharleswilson
social:
  name: Jake Wilson
  links:
    - https://www.instagram.com/jcbchrlswlsn
    - https://github.com/jkwlsn
    - https://www.linkedin.com/jacobcharleswilson
lang: en_GB
permalink: ":title:output_ext"
markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

cdn_url: https://jkwlsn.dev/

plugins:
- jekyll-seo-tag
- jekyll-sitemap

# Default Post Front Matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: post
      author: Jake Wilson
      language: English # A language of the resource.
